language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
script: nosetests --with-coverage --cover-package=. --cover-erase
after_success:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install python-coveralls && coveralls
    fi
