sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
cache: pip
install: pip install coverage
script: nosetests --with-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
