#!/bin/sh

git submodule update --recursive

`git rev-parse --show-toplevel`/tools/developer_tools/cleanup_pyc.py
`git rev-parse --show-toplevel`/tools/developer_tools/setup_cmake.py > /dev/null
rm -f `git rev-parse --show-toplevel`/VERSION
