#!/bin/sh

git submodule update --recursive

`git rev-parse --show-toplevel`/tools/developer_tools/cleanup-pycs.py
`git rev-parse --show-toplevel`/tools/developer_tools/setup-cmake.py > /dev/null
rm -f `git rev-parse --show-toplevel`/VERSION
